export const FETCHING_COIN_SUCCESS = "FETCHING_COIN_SUCCESS";
export const FETCHING_ALL_COIN_SUCCESS = "FETCHING_ALL_COIN_SUCCESS";
export const FETCHING_COIN = "FETCHING_COIN";
export const FETCHING_COIN_FAILURE = "FETCHING_COIN_FAILURE";
export const FETCHING_ALL_COIN_FAILURE = "FETCHING_ALL_COIN_FAILURE";
export const SEARCH_COIN = "FETCHING_COIN_FAILURE";
